<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
   <!-- Bootstrap CSS -->
      <!-- build:css css/main.css -->
      <link rel="stylesheet" href="node_modules/bootstrap/dist/css/bootstrap.min.css">
      
      <link rel="stylesheet" href="node_modules/bootstrap-social/bootstrap-social.css">
      
     

      <link rel="stylesheet" href="node_modules/font-awesome/css/font-awesome.min.css">
      <link rel="stylesheet" href="css/styles.css">
      <link rel="stylesheet" href="css/jquery.dataTables.min.css">
      <script src="node_modules/jquery/dist/jquery.min.js"></script>
      <script src="node_modules/infinite-scroll/dist/infinite-scroll.pkgd.min.js"></script>
      <link rel="stylesheet" href="node_modules/gridjs/dist/theme/mermaid.min.css">
      <script src="js/jquery.dataTables.min.js"></script>
      <!-- end build -->
  <title><?=$title?></title>
</head>

   

  <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #0d47a1;">
  <a style="color: white;" class="navbar-brand" href="index.php">Solution challenge Smart DPU</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarText">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a style="color: #020015ff;" class="nav-link" href="index.php">Accueil </a>
      </li>
      <li class="nav-item">
        <a style="color: #000000ff;" class="nav-link" href="add.php">Ajouter Patient</a>
        </li>
       
    </ul>
  </div>
  </nav>
  <body >
  <div style="background-color: #072552ff;color:white; 
 " class="text-center">
    <h1  class="display-4">
    Solution challenge Smart DPU
    </h1>

  </div>
  
   <?php include $template . '.phtml'; ?>
  
</body>
<!-- Footer -->
<footer style="color: white; background-color: #072552ff;" class="page-footer font-small">

  <!-- Copyright -->
  <div class="footer-copyright text-center py-3">© 2025 Copyright:
    <a href="https://www.linkedin.com/in/tasnim-chekir-302188352/"> Tasnim chekir</a>
  </div>
  <!-- Copyright -->

</footer>
<!-- Footer -->

<script src="node_modules/gridjs-jquery/dist/gridjs.production.min.js"></script>
<script src="js/grid-table.js"></script>

 <script src="node_modules/popper.js/dist/umd/popper.min.js"></script>
 <script src="node_modules/bootstrap/dist/js/bootstrap.min.js"></script>

</script>
</html>
