<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="index.php">Home</a></li>
    <li style="cursor: pointer;" onclick="history.back()" class="breadcrumb-item active" aria-current="page">Retour vers Patient</li>
  </ol>
</nav>
<form method="POST" action='/Solution-challenge-Smart-DPU-GDSC-ISTMT/save_note.php'>
				<div class="form-group">
          <input type="hidden" id="note_id" name='note_id' value='<?= $_GET['noteId']?>'/>
				</div>
				<div class="form-group offset-1 col-10">
					<label>Consultation</label>
					<textarea id="content" name="content" class="form-control" style=" height:200px;">
                <?= $note['Note'] ?>
                </textarea>
				</div>
				<div id="result"></div>
				<br />
				<center><button type="submit" id="save" class="btn btn-primary">
          <span class="glyphicon glyphicon-save">

          </span> Save Consultation</button>
        </center>
			</form>
      <script type="text/javascript">
	function autoSave()
	{
		var content = document.getElementById('content').value;
		var note_id = document.getElementById('note_id').value;
	
			$.ajax({
				url:'update_note.php',
				method:"post",
				data:{content : content,note_id:note_id},
				success:function(response)
				{
					
					document.getElementById('result').innerHTML="Notes  Saved.";
				
				}
			});
		
	}
	setInterval(function(){
		autoSave();
	},8000);

		setInterval(function(){
						document.getElementById('result').innerHTML="";
					},8000);
</script>
